version: "3.9"

services:
  crawler:
    image: python:3.9-slim
    container_name: crawler
    volumes:
      - ./:/crawler/
    working_dir: /crawler/
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=changeme
      - PG_URI=host.docker.internal:5432
    command: >
      bash -c "apt-get update 
      && apt-get install -y libpq-dev gcc
      && pip install --upgrade pip==22.0.3
      && pip install -r requirements.txt"